#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

ZSH_HIGHLIGHT_STYLES[path]='fg=cyan'
ZSH_HIGHLIGHT_STYLES[alias]='fg=magenta,bold'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=magenta'

ZSH_HIGHLIGHT_PATTERNS+=('rm -rf *' 'fg=white,bold,bg=red')

alias l='ls -lh'
alias la='ls -lah'
alias lsd='ls -d *(/)'
alias reboot='sync;reboot'
alias shutdown='sync;shutdown -h now'
alias rm='nocorrect rm'
#alias sd='sudo'
alias snano='sudo nano'
alias virsh='EDITOR=/usr/bin/nano virsh'

#---

export EDITOR='nano'
export VISUAL='nano'
export PAGER='less'

source <(kubectl completion zsh)


if [[ -e "/google/google-cloud-sdk/completion.zsh.inc" ]]; then
  source "/google/google-cloud-sdk/completion.zsh.inc"
fi
onexit () {
  for FILE in /google/devshell/bash_exit.google.d/*; do
    if [ -x "$FILE" ]; then
      "$FILE"
    fi
  done
}
trap onexit EXIT

alias wpctl=$HOME/wp-configuration/k8s/wpctl
alias cedit='cloudshell edit'

TRANSFERSH_URL=https://transfer.sh
export EDITOR=nano

# because of missing highlight: https://github.com/zsh-users/zsh-autosuggestions/issues/229 
# export TERM=xterm-256color
# But this does not work. This is requied:
# 
# echo set -g default-terminal xterm-256color >> ~/.tmux.conf

#### Place here machine specific settings:
# ~/.config/zshrc

if [[ -s "${ZDOTDIR:-$HOME}/.config/zshrc.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.config/zshrc.zsh"
fi

function transfer {
    curl --progress-bar --upload-file "$1" $TRANSFERSH_URL/$(basename "$1") | tee /dev/null;
    echo
}
alias transfer=transfer
